# Should be called on pull_requests
name: Flutter PR Checks

on:
  # This line allows the workflow to be called by other workflows
  workflow_call:
    secrets:
      FIREBASE_OPTIONS_DART:
        required: true
      GOOGLE_SERVICES_JSON: # If provided, will build for android
        required: false
      GOOGLE_SERVICE_INFO_PLIST: # If provided, will build for iOS
        required: false

# https://medium.com/@colonal/automating-flutter-builds-and-releases-with-github-actions-77ccf4a1ccdd
jobs:
  build:
    runs-on: ubuntu-latest # macos-latest if needing an ios build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For android builds
      # Duration: ~3 minutes
      - name: Set Up Java
        if: ${{ github.event.secrets.GOOGLE_SERVICES_JSON != '' }}
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Create Firebase Options file (lib/firebase_options.dart)
        # run: |
        #   echo "${{ github.event.secrets.FIREBASE_OPTIONS_DART }}" > lib/firebase_options.dart
        # run: |
        #   # Use heredoc syntax for robust multi-line file creation
        #   cat << EOF > lib/firebase_options.dart
        #   ${{ github.event.secrets.FIREBASE_OPTIONS_DART }}
        #   EOF
        run: |
          echo "${{ github.event.secrets.FIREBASE_OPTIONS_DART }}" | base64 --decode > lib/firebase_options.dart
        shell: bash

      - name: Debug Firebase Options file
        run: cat lib/firebase_options.dart

      - name: Create Google Services JSON (android/app/google-services.json)
        if: ${{ github.event.secrets.GOOGLE_SERVICES_JSON != '' }}
        run: |
          mkdir -p android/app/
          echo "${{ github.event.secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json
        shell: bash

      - name: Create GoogleService-Info.plist (ios/Runner/GoogleService-Info.plist)
        if: ${{ github.event.secrets.GOOGLE_SERVICE_INFO_PLIST != '' }}
        run: |
          mkdir -p ios/Runner/
          echo "${{ github.event.secrets.GOOGLE_SERVICE_INFO_PLIST }}" > ios/Runner/GoogleService-Info.plist
        shell: bash

      - name: Install dependencies
        run: flutter pub get

      # TODO : only triggered by wo_form_example
      - name: Update wo_form version file
        run: dart lib/wo_form_version/generate_version.dart

      - name: Build Flutter Web
        run: flutter build web

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
