# Should be called on pull_requests
name: Flutter PR Checks

# https://medium.com/@colonal/automating-flutter-builds-and-releases-with-github-actions-77ccf4a1ccdd
jobs:
  build:
    runs-on: ubuntu-latest # macos-latest if needing an ios build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For android builds
      # Duration: ~3 minutes
      # - name: Set Up Java
      #   uses: actions/setup-java@v3.12.0
      #   with:
      #     distribution: "oracle"
      #     java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Create dotenv file
        run: echo "${{ secrets.DOTENV_FILE }}" > dotenv

      - name: Update wo_form version file
        run: dart lib/wo_form_version/generate_version.dart

      - name: Build Flutter Web
        run: flutter build web

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
